/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        ink: '#000000',
        canvas: '#ffffff',
        'inverse-canvas': '#000000',
        'inverse-ink': '#ffffff',
        'surface-soft': '#f7f7f5',
        hairline: '#e6e6e6',
        'hairline-soft': '#f1f1f1',
        'block-lime': '#dceeb1',
        'block-lilac': '#c5b0f4',
        'block-cream': '#f4ecd6',
        'block-pink': '#efd4d4',
        'block-mint': '#c8e6cd',
        'block-coral': '#f3c9b6',
        'block-navy': '#1f1d3d',
        'accent-magenta': '#ff3d8b',
        'semantic-success': '#1ea64a',
        'semantic-error': '#e53935',
        'semantic-warning': '#f59e0b',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['86px', { lineHeight: '1.00', letterSpacing: '-1.72px' }],
        'display-lg': ['64px', { lineHeight: '1.10', letterSpacing: '-0.96px' }],
        headline: ['26px', { lineHeight: '1.35', letterSpacing: '-0.26px' }],
        subhead: ['26px', { lineHeight: '1.35', letterSpacing: '-0.26px' }],
        'card-title': ['24px', { lineHeight: '1.45', letterSpacing: '0' }],
        'body-lg': ['20px', { lineHeight: '1.40', letterSpacing: '-0.14px' }],
        body: ['18px', { lineHeight: '1.45', letterSpacing: '-0.26px' }],
        'body-sm': ['16px', { lineHeight: '1.45', letterSpacing: '-0.14px' }],
        eyebrow: ['13px', { lineHeight: '1.30', letterSpacing: '0.54px' }],
        caption: ['12px', { lineHeight: '1.00', letterSpacing: '0.60px' }],
      },
      borderRadius: {
        xs: '2px',
        sm: '6px',
        md: '8px',
        lg: '24px',
        xl: '32px',
        pill: '50px',
        full: '9999px',
      },
      spacing: {
        hair: '1px',
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      maxWidth: {
        content: '1280px',
      },
      boxShadow: {
        'elevation-1': '0 0 0 1px #e6e6e6',
        'elevation-2': '0 4px 16px rgba(0,0,0,0.06)',
        'elevation-3': '0 8px 32px rgba(0,0,0,0.12)',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        'marquee': 'marquee 20s linear infinite',
      },
    },
  },
  plugins: [],
}
